### ISSUE TITLE
.NET 7 not working: "The format of value '' is invalid"

### ISSUE THREAD

**Issue by drhumlen** [fsprojects/FsHttp#114] opened 2022-11-09 19:50 UTC
After upgrade to .NET 7, FsHttp seems to struggle with parsing headers:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (The format of value '' is invalid.)
 ---> System.FormatException: The format of value '' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
```

Example for reproduction:

```
open FsHttp

let req = http {
    GET "http://google.com"
}

let res = Request.send req

printfn $"res = %A{res}"
```

**Comment by RonaldSchlenker** [comment] 2022-11-12 10:13
This is a duplicate of #109  - anyway, thank you @drhumlen for reporting it.

I've released 10.0.0-preview2. See related PR and Commits...

**Closed** 2022-11-25 10:07 UTC
